### ISSUE TITLE
Add config file to specify a single server

### ISSUE THREAD

**Issue by dgutman** [Mmasoud1/OME-Channels-Organizer#1]
![image](https://user-images.githubusercontent.com/713166/93531103-acaa7f00-f90c-11ea-88f2-b235fa3dc004.png)

Add something to config.json or equivalent to have a "single server" mode where

1) It doesn't ask you which server to use.. it just uses the default server.  Basically just skips the Host-collection tab

**Comment by Mmasoud1** [comment]
Resolved by choosing first server by default. Next to add that option to the settings window
